from xml.dom.minidom import parse
import argparse


def main() -> None:
    parser = argparse.ArgumentParser(description='Fix DRA file generated by inFakt')
    parser.add_argument('dra_file', help='DRA file name')
    parser.add_argument('--id', help='Add provided Polish ID card')
    parser.add_argument('--passport', help='Add provided Polish passport')
    args = parser.parse_args()


if __name__ == '__main__':
    main()
